services:
  db:
    image: postgres
    restart: always
    container_name: example-db
    ports:
      - '9864:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: example
    healthcheck:
      test: pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 5s
      timeout: 60s
      retries: 5
